### ISSUE TITLE
Permission check needs to be present before loading images.

### ISSUE THREAD

**Issue by st1hy** [st1hy/Count-Them-Calories#8]
Currently permission for write external storage is asked and requested when selecting image to be added to new meal or ingredient.

If user revokes permission and restarts the app images do not load leaving empty spaces.

Solution:
1. Check and ask permission before loading images.
2. If permission is not granted use default images, do not attempt reading external storage.

**Comment by maffiemouw** [comment]
[wordpress-mobile-pack.2.2.4.zip](https://github.com/st1hy/Count-Them-Calories/files/378955/wordpress-mobile-pack.2.2.4.zip)
